PB EQU 31H
CB EQU 33H
PIC EQU 20H
TIMER EQU 10H
N_CLK EQU 10

ORG 1000H
INICIO DB 1,2,4,8,16,32,64,128,64,32,16,8,4,2,1
FIN DB ?

ORG 40
IP_CLK DW RUT_CLK

ORG 3000H
RUT_CLK: PUSH AX
         CMP BX,OFFSET FIN
         JNZ LUCES
         MOV BX,OFFSET INICIO
  LUCES: INC BX
         MOV AL,[BX]
         OUT PB,AL
         MOV AL,0
         OUT TIMER,AL; CONT=0
         MOV AL,PIC; FIN DE
         OUT PIC,AL; INTERRUPCION
         POP AX
         IRET

ORG 2000H
CLI
MOV AL,00H
OUT CB,AL; Todo salida
OUT PB,AL; Todas luces apagadas
MOV AL, 0FDH
OUT PIC+1,AL; IMR=1111 11101
MOV AL,N_CLK
OUT PIC+5,AL; INT1=10
MOV AL,1
OUT TIMER+1,AL; COMP=1
MOV AL,0
OUT TIMER,AL; CONT=0
STI
MOV BX, OFFSET INICIO
LAZO: JMP LAZO
INT 0 
END